blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail'),
]

django_portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portafolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)  # type: ignore

portafolio/models.py
from django.db import models


# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='portafolio/images/')
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.


def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {
        'posts': posts
    })


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {
        'post': post
    })

portafolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {
        'projects': projects
    })

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<h1>Post_detail</h1>

<h3>{{post.title}}</h3>
<h4 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h4>
<div class="text-center"> 
  <img
    src="{{post.image.url}}"
    class="img-fluid"
    alt="{{post.title}}"
  />
  
  <div class="my-4">
    <p>{{post.description|safe}}</p>
  </div>
  
</div> 
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

<h1>Posts</h1>


{% for post in posts %}

  <div class="p-3">
    <div class="card card-body bg-black">
      <div class="row">
        <div class="col-3">
          <img src="{{post.image.url}}" class="img-fluid" alt="{{post.title}}">
        </div>
        <div class="col-9">
          <h3>{{post.title}}</h3>
      <p>{{post.date|date:'M d Y'}}</p>
      <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary"> Ver detalle</a>
        </div>
      </div>
    </div>
  </div>
{% endfor%}

{% endblock %}

portafolio/templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

<header class="row bg-black">
  <div class="col-md-4">
    <img src="{% static 'portafolio/Logo.jpg' %}" height="250px" width="250px" alt="Perfil">
  </div>
  <div class="col-md-8 my-auto">
    <h3><strong>Marisquería Chávez</strong></h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Aspernatur earum voluptatum vitae cupiditate facere amet omnis quam magni voluptatibus rem tenetur, dignissimos perspiciatis atque? Harum a in dolorum cum eveniet!</p>
    <a class="btn btn-primary btn-sm" href="{% static 'portafolio/Menu.pdf' %}" target="_blank">Download PDF</a>
  </div>
</header>

<div class="row my-4 text-center">  
  <h3>My blogs</h3>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
    Quia, et iusto consequatur magnam optio sunt at accusamus soluta ab doloremque nam molestiae mollitia cum necessitatibus itaque sapiente laborum dolor tempora?</p>
  {% for project in projects %}

    <div class="col-md-4 p-4">
      <div class="card bg-black card-project">
        <img src="{{project.image.url}}" class="card-img-top" alt="{{project.title}}">
        <div class="card-body">
          <h2>{{project.title}}</h2> 
          <p>{{rpoject.description}}</p>
          <a class="btn btn-secondary rounded btn-sm" href="{{project.url}}" target="_blank">{{project.url}}</a>
        </div>
      </div>
    </div>

  {% endfor %}
</div>

{%endblock%}

portafolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django App</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    />
    <link rel="stylesheet" href="{% static 'main.css' %}">
  </head>
  <body class="text-light">
    {% include 'partials/navbar.html' %}

    <div class="container p-4">
      {% block content %} {% endblock %}

    </div>
    
    
  </body>
</html>

portafolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand fw-bold" href="{% url 'home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">SignUp</a>
        </li>
      </ul>
    </div>
  </div>
</nav>